import { defineConfig, type RollupOptions } from 'rollup';
import { dts as plugin_dts } from 'rollup-plugin-dts';

import mobx_package from 'mobx/package.json' with { type: 'json' };

const FILES_PATH = 'files/auto-dark-light@gihaume/5.8'

export default defineConfig([
    {
        input: 'node_modules/mobx/dist/mobx.esm.development.js',
        treeshake: false,
        output: {
            file: `${FILES_PATH}/src/lib/mobx.js`,
            format: 'es',
            banner: `// mobx v${mobx_package.version}, automatically generated by Rollup`,
            outro: 'configure({ isolateGlobalState: true });', // Cinnamon shares one globalThis across all applets
        },
    },
    {
        input: 'node_modules/mobx/dist/mobx.d.ts',
        plugins: [plugin_dts({ respectExternal: true })],
        output: {
            file: `${FILES_PATH}/src/lib/mobx.d.ts`,
            format: 'es',
            banner: `// mobx v${mobx_package.version}, automatically generated by rollup-plugin-dts`,
        },
    },
] satisfies RollupOptions[]);
