// THIS FILE IS AUTOGENERATED!
const { panelManager, layoutManager } = imports.ui.main
const { getAppletDefinition } = imports.ui.appletManager;
const {radioApplet} = require('./radio-applet');
    
function main(metadata, orientation, panel_height, instance_id) {
    __meta.instanceId = instance_id
    __meta.orientation = orientation

    const appletDefinition = getAppletDefinition({applet_id: instance_id})
    const panel = panelManager.panels.find(panel => panel?.panelId === appletDefinition.panelId)
    const locationLabel = appletDefinition.location_label
    const monitor = layoutManager.findMonitorForActor(panel.actor)

    __meta.panel = panel
    __meta.locationLabel = locationLabel
    __meta.monitor = monitor

    return new radioApplet.main();
}