"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MAX_STRING_LENGTH = exports.LOADING_ICON_NAME = exports.DOWNLOAD_ICON_NAME = exports.COPY_ICON_NAME = exports.SONG_INFO_ICON_NAME = exports.STOP_ICON_NAME = exports.PAUSE_ICON_NAME = exports.PLAY_ICON_NAME = exports.RADIO_SYMBOLIC_ICON_NAME = exports.MAX_VOLUME = exports.MPV_MPRIS_BUS_NAME = exports.MEDIA_PLAYER_2_PATH = exports.MEDIA_PLAYER_2_PLAYER_NAME = exports.MEDIA_PLAYER_2_NAME = exports.MPRIS_PLUGIN_URL = exports.MPRIS_PLUGIN_PATH = exports.CONFIG_DIR = exports.DEFAULT_TOOLTIP_TXT = exports.APPLET_SITE = void 0;
const { get_home_dir } = imports.gi.GLib;
exports.APPLET_SITE = 'https://cinnamon-spices.linuxmint.com/applets/view/297';
exports.DEFAULT_TOOLTIP_TXT = 'Radio++';
exports.CONFIG_DIR = `${get_home_dir()}/.cinnamon/configs/${__meta.uuid}`;
exports.MPRIS_PLUGIN_PATH = exports.CONFIG_DIR + '/.mpris.so';
exports.MPRIS_PLUGIN_URL = "https://github.com/hoyon/mpv-mpris/releases/download/0.5/mpris.so";
exports.MEDIA_PLAYER_2_NAME = "org.mpris.MediaPlayer2";
exports.MEDIA_PLAYER_2_PLAYER_NAME = "org.mpris.MediaPlayer2.Player";
exports.MEDIA_PLAYER_2_PATH = "/org/mpris/MediaPlayer2";
exports.MPV_MPRIS_BUS_NAME = `${exports.MEDIA_PLAYER_2_NAME}.mpv`;
exports.MAX_VOLUME = 100;
exports.RADIO_SYMBOLIC_ICON_NAME = 'radioapplet';
const PLAYBACK_ICON_PREFIX = 'media-playback';
exports.PLAY_ICON_NAME = `${PLAYBACK_ICON_PREFIX}-start`;
exports.PAUSE_ICON_NAME = `${PLAYBACK_ICON_PREFIX}-pause`;
exports.STOP_ICON_NAME = `${PLAYBACK_ICON_PREFIX}-stop`;
exports.SONG_INFO_ICON_NAME = 'audio-x-generic';
exports.COPY_ICON_NAME = 'edit-copy';
exports.DOWNLOAD_ICON_NAME = 'south-arrow-weather-symbolic';
exports.LOADING_ICON_NAME = 'view-refresh-symbolic';
exports.MAX_STRING_LENGTH = 40;
