[general]
lower_cutoff_freq = 30
higher_cutoff_freq = 18000
autosens = 0
bars = 120
framerate = 25
sensitivity = 650

[input]
method = pulse
source = auto

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100
bar_delimiter = 59
frame_delimiter = 10
channels = stereo
method = raw
data_format = ascii

[smoothing]
noise_reduction = 0
integral = 0
monstercat = 0
gravity = 400

[eq]
1 = 1.10
2 = 1.00
3 = 0.90
4 = 0.82
5 = 0.75
