// mobx v7.0.0, automatically generated by rollup-plugin-dts
interface Lambda {
    (): void;
    name?: string;
}

declare const $mobx: unique symbol;
interface IAtom extends IObservable {
    reportObserved(): boolean;
    reportChanged(): void;
}
declare class Atom implements IAtom {
    name_: string;
    private flags_;
    observers_: Set<IDerivation>;
    lastAccessedBy_: number;
    lowestObserverState_: IDerivationState_;
    /**
     * Create a new atom. For debugging purposes it is recommended to give it a name.
     * The onBecomeObserved and onBecomeUnobserved callbacks can be used for resource management.
     */
    constructor(name_?: string);
    get isBeingObserved(): boolean;
    set isBeingObserved(newValue: boolean);
    get isPendingUnobservation(): boolean;
    set isPendingUnobservation(newValue: boolean);
    get diffValue(): 0 | 1;
    set diffValue(newValue: 0 | 1);
    onBOL: Set<Lambda> | undefined;
    onBUOL: Set<Lambda> | undefined;
    onBO(): void;
    onBUO(): void;
    /**
     * Invoke this method to notify mobx that your atom has been used somehow.
     * Returns true if there is currently a reactive context.
     */
    reportObserved(): boolean;
    /**
     * Invoke this method _after_ this method has changed to signal mobx that all its observers should invalidate.
     */
    reportChanged(): void;
    toString(): string;
}
declare function createAtom(name: string, onBecomeObservedHandler?: () => void, onBecomeUnobservedHandler?: () => void): IAtom;

interface IEqualsComparer<T> {
    (a: T, b: T): boolean;
}
declare function compareIdentity(a: any, b: any): boolean;
declare function compareStructural(a: any, b: any): boolean;
declare function compareShallow(a: any, b: any): boolean;
declare const compareDefault: (value1: any, value2: any) => boolean;

interface IEnhancer<T> {
    (newValue: T, oldValue: T | undefined, name: string): T;
}

declare const override: Annotation;

interface GenericAbortSignal {
    readonly aborted: boolean;
    onabort?: ((...args: any) => any) | null;
    addEventListener?: (...args: any) => any;
    removeEventListener?: (...args: any) => any;
}

declare const enum MakeResult {
    Cancel = 0,
    Break = 1,
    Continue = 2
}
type Annotation = {
    annotationType_: string;
    make_(adm: ObservableObjectAdministration, key: PropertyKey, descriptor: PropertyDescriptor, source: object): MakeResult;
    extend_(adm: ObservableObjectAdministration, key: PropertyKey, descriptor: PropertyDescriptor, proxyTrap: boolean): boolean | null;
    options_?: any;
};
type AnnotationMapEntry = Annotation | true | false;
type AnnotationsMap<T, AdditionalFields extends PropertyKey> = {
    [P in Exclude<keyof T, "toString">]?: AnnotationMapEntry;
} & Record<AdditionalFields, AnnotationMapEntry>;

type DecoratorAnnotation<Decorator extends (...args: any[]) => any> = Annotation & Decorator;

type ClassAccessorDecorator<This = any, Value = any> = (value: ClassAccessorDecoratorTarget<This, Value>, context: ClassAccessorDecoratorContext) => ClassAccessorDecoratorResult<This, Value> | void;
type ClassGetterDecorator<This = any, Value = any> = (value: (this: This) => Value, context: ClassGetterDecoratorContext) => ((this: This) => Value) | void;
type ClassMethodDecorator<This = any, Value extends (...p: any[]) => any = any> = (value: Value, context: ClassMethodDecoratorContext<This, Value>) => Value | void;
type ClassFieldDecorator<This = any, Value extends (...p: any[]) => any = any> = (value: Value, context: ClassFieldDecoratorContext<This, Value>) => Value | void;
type ClassMethodAndFieldDecorator = ClassMethodDecorator & ClassFieldDecorator;
type ClassAccessorAndFieldDecorator = ClassAccessorDecorator & ClassFieldDecorator;

type CreateObservableOptions = {
    name?: string;
    equals?: IEqualsComparer<any>;
    deep?: boolean;
    defaultDecorator?: Annotation;
    autoBind?: boolean;
};
interface IObservableValueFactory {
    <T>(value: T, options?: CreateObservableOptions): IObservableValue<T>;
    <T>(value?: T, options?: CreateObservableOptions): IObservableValue<T | undefined>;
}
interface IObservableMapFactory {
    <K = any, V = any>(): ObservableMap<K, V>;
    <K, V>(initialValues?: IMapEntries<K, V>, options?: CreateObservableOptions): ObservableMap<K, V>;
    <K, V>(initialValues?: IReadonlyMapEntries<K, V>, options?: CreateObservableOptions): ObservableMap<K, V>;
    <K, V>(initialValues?: IKeyValueMap<V>, options?: CreateObservableOptions): ObservableMap<K, V>;
    <K, V>(initialValues?: Map<K, V>, options?: CreateObservableOptions): ObservableMap<K, V>;
    <K = any, V = any>(initialValues: undefined, options?: CreateObservableOptions): ObservableMap<K, V>;
}
interface IObservableFactory extends Annotation, ClassAccessorAndFieldDecorator {
    <T = any>(value: T[], options?: CreateObservableOptions): IObservableArray<T>;
    <T = any>(value: Set<T>, options?: CreateObservableOptions): ObservableSet<T>;
    <K = any, V = any>(value: Map<K, V>, options?: CreateObservableOptions): ObservableMap<K, V>;
    <T extends object>(value: T, annotations?: AnnotationsMap<T, never>, options?: CreateObservableOptions): T;
    box: IObservableValueFactory;
    array: <T = any>(initialValues?: T[], options?: CreateObservableOptions) => IObservableArray<T>;
    set: <T = any>(initialValues?: IObservableSetInitialValues<T>, options?: CreateObservableOptions) => ObservableSet<T>;
    map: IObservableMapFactory;
    object: <T = any>(props: T, annotations?: AnnotationsMap<T, never>, options?: CreateObservableOptions) => T;
}
declare const observableRef: DecoratorAnnotation<ClassAccessorAndFieldDecorator>;
declare const observableShallow: DecoratorAnnotation<ClassAccessorAndFieldDecorator>;
declare const observableDeep: DecoratorAnnotation<ClassAccessorAndFieldDecorator>;
declare const observableStruct: DecoratorAnnotation<ClassAccessorAndFieldDecorator>;
declare var observable: IObservableFactory;

interface IComputedFactory extends Annotation, ClassGetterDecorator {
    <T>(options: IComputedValueOptions<T>): DecoratorAnnotation<ClassGetterDecorator>;
    <T>(func: () => T, options?: IComputedValueOptions<T>): IComputedValue<T>;
}
declare const computedStruct: DecoratorAnnotation<ClassGetterDecorator>;
declare const computed: IComputedFactory;

interface IActionRunInfo {
    prevDerivation_: IDerivation | null;
    prevAllowStateChanges_: boolean;
    prevAllowStateReads_: boolean;
    notifySpy_: boolean;
    startTime_: number;
    error_?: any;
    parentActionId_: number;
    actionId_: number;
    runAsAction_?: boolean;
}
declare function _startAction(actionName: string, canRunAsDerivation: boolean, // true for autoAction
scope: any, args?: IArguments): IActionRunInfo;
declare function _endAction(runInfo: IActionRunInfo): void;
declare function allowStateChanges<T>(allowStateChanges: boolean, func: () => T): T;

interface IValueWillChange<T> {
    object: IObservableValue<T>;
    type: "update";
    newValue: T;
}
type IValueDidChange<T = any> = {
    type: "update";
    observableKind: "value";
    object: IObservableValue<T>;
    debugObjectName: string;
    newValue: T;
    oldValue: T | undefined;
};
type IBoxDidChange<T = any> = {
    type: "create";
    observableKind: "value";
    object: IObservableValue<T>;
    debugObjectName: string;
    newValue: T;
} | IValueDidChange<T>;
interface IObservableValue<T> {
    get(): T;
    set(value: T): void;
}
declare class ObservableValue<T> extends Atom implements IObservableValue<T>, IInterceptable<IValueWillChange<T>>, IListenable {
    enhancer_: IEnhancer<T>;
    name_: string;
    private equals_;
    hasUnreportedChange_: boolean;
    interceptors_: any;
    changeListeners_: any;
    value_: any;
    dehancer: any;
    constructor(value: T, enhancer_: IEnhancer<T>, name_?: string, notifySpy?: boolean, equals_?: IEqualsComparer<any>);
    private dehanceValue;
    set(newValue: T): void;
    private prepareNewValue_;
    setNewValue_(newValue: T): void;
    get(): T;
    raw(): any;
    toJSON(): T;
    toString(): string;
    valueOf(): T;
    [Symbol.toPrimitive](): T;
}
declare const isObservableValue: (x: any) => x is IObservableValue<any>;

interface IComputedValue<T> {
    get(): T;
    set(value: T): void;
}
interface IComputedValueOptions<T> {
    get?: () => T;
    set?: (value: T) => void;
    name?: string;
    equals?: IEqualsComparer<T>;
    context?: any;
    requiresReaction?: boolean;
    keepAlive?: boolean;
}
type IComputedDidChange<T = any> = {
    type: "update";
    observableKind: "computed";
    object: unknown;
    debugObjectName: string;
    newValue: T;
    oldValue: T | undefined;
};
declare class ComputedValue<T> implements IObservable, IComputedValue<T>, IDerivation {
    dependenciesState_: IDerivationState_;
    observing_: IObservable[];
    newObserving_: null;
    observers_: Set<IDerivation>;
    runId_: number;
    lastAccessedBy_: number;
    lowestObserverState_: IDerivationState_;
    unboundDepsCount_: number;
    protected value_: T | undefined | CaughtException;
    name_: string;
    triggeredBy_?: string;
    private flags_;
    derivation: () => T;
    setter_?: (value: T) => void;
    scope_: Object | undefined;
    private equals_;
    private requiresReaction_;
    keepAlive_: boolean;
    /**
     * Create a new computed value based on a function expression.
     *
     * The `name` property is for debug purposes only.
     *
     * The `equals` property specifies the comparer function used to determine if a newly produced
     * value differs from the previous value. Structural comparison can be convenient if you always
     * produce a new aggregated object and don't want to notify observers if it is structurally the same.
     * This is useful for working with vectors, mouse coordinates etc.
     */
    constructor(options: IComputedValueOptions<T>);
    onBecomeStale_(): void;
    onBOL: Set<Lambda> | undefined;
    onBUOL: Set<Lambda> | undefined;
    onBO(): void;
    onBUO(): void;
    private get isComputing();
    private set isComputing(value);
    private get isRunningSetter();
    private set isRunningSetter(value);
    get isBeingObserved(): boolean;
    set isBeingObserved(newValue: boolean);
    get isPendingUnobservation(): boolean;
    set isPendingUnobservation(newValue: boolean);
    get diffValue(): 0 | 1;
    set diffValue(newValue: 0 | 1);
    /**
     * Returns the current value of this computed value.
     * Will evaluate its computation first if needed.
     */
    get(): T;
    set(value: T): void;
    trackAndCompute(): boolean;
    computeValue_(track: boolean): T | CaughtException;
    suspend_(): void;
    warnAboutUntrackedRead_(): void;
    toString(): string;
    valueOf(): T;
    [Symbol.toPrimitive](): T;
}

declare const enum IDerivationState_ {
    NOT_TRACKING_ = -1,
    UP_TO_DATE_ = 0,
    POSSIBLY_STALE_ = 1,
    STALE_ = 2
}
/**
 * A derivation is everything that can be derived from the state (all the atoms) in a pure manner.
 * See https://medium.com/@mweststrate/becoming-fully-reactive-an-in-depth-explanation-of-mobservable-55995262a254#.xvbh6qd74
 */
interface IDerivation extends IDepTreeNode {
    observing_: IObservable[];
    newObserving_: null | IObservable[];
    dependenciesState_: IDerivationState_;
    /**
     * Id of the current run of a derivation. Each time the derivation is tracked
     * this number is increased by one. This number is globally unique
     */
    runId_: number;
    /**
     * amount of dependencies used by the derivation in this run, which has not been bound yet.
     */
    unboundDepsCount_: number;
    onBecomeStale_(): void;
    /**
     *  warn if the derivation has no dependencies after creation/update
     */
    requiresObservable_?: boolean;
}
declare class CaughtException {
    cause: any;
    constructor(cause: any);
}
declare function isComputingDerivation(): boolean;
declare function untracked<T>(action: () => T): T;
declare function allowStateReadsStart(allowStateReads: boolean): boolean;
declare function allowStateReadsEnd(prev: boolean): void;

declare function getGlobalState(): any;
/**
 * For testing purposes only; this will break the internal state of existing observables,
 * but can be used to get back at a stable state after throwing errors
 */
declare function resetGlobalState(): void;

interface IDepTreeNode {
    name_: string;
    observing_?: IObservable[];
}
interface IObservable extends IDepTreeNode {
    diffValue: number;
    /**
     * Id of the derivation *run* that last accessed this observable.
     * If this id equals the *run* id of the current derivation,
     * the dependency is already established
     */
    lastAccessedBy_: number;
    isBeingObserved: boolean;
    lowestObserverState_: IDerivationState_;
    isPendingUnobservation: boolean;
    observers_: Set<IDerivation>;
    onBUO(): void;
    onBO(): void;
    onBUOL: Set<Lambda> | undefined;
    onBOL: Set<Lambda> | undefined;
}

/**
 * Reactions are a special kind of derivations. Several things distinguishes them from normal reactive computations
 *
 * 1) They will always run, whether they are used by other computations or not.
 * This means that they are very suitable for triggering side effects like logging, updating the DOM and making network requests.
 * 2) They are not observable themselves
 * 3) They will always run after any 'normal' derivations
 * 4) They are allowed to change the state and thereby triggering themselves again, as long as they make sure the state propagates to a stable state in a reasonable amount of iterations.
 *
 * The state machine of a Reaction is as follows:
 *
 * 1) after creating, the reaction should be started by calling `runReaction` or by scheduling it (see also `autorun`)
 * 2) the `onInvalidate` handler should somehow result in a call to `this.track(someFunction)`
 * 3) all observables accessed in `someFunction` will be observed by this reaction.
 * 4) as soon as some of the dependencies has changed the Reaction will be rescheduled for another run (after the current mutation or transaction). `isScheduled` will yield true once a dependency is stale and during this period
 * 5) `onInvalidate` will be called, and we are back at step 1.
 *
 */
interface IReactionPublic {
    dispose(): void;
}
interface IReactionDisposer {
    (): void;
    [$mobx]: Reaction;
}
declare class Reaction implements IDerivation, IReactionPublic {
    name_: string;
    private onInvalidate_;
    private errorHandler_?;
    requiresObservable_?: any;
    observing_: IObservable[];
    newObserving_: IObservable[];
    dependenciesState_: IDerivationState_;
    runId_: number;
    unboundDepsCount_: number;
    private flags_;
    constructor(name_: string | undefined, onInvalidate_: () => void, errorHandler_?: ((error: any, derivation: IDerivation) => void) | undefined, requiresObservable_?: any);
    get isDisposed(): boolean;
    set isDisposed(newValue: boolean);
    get isScheduled(): boolean;
    set isScheduled(newValue: boolean);
    get isTrackPending(): boolean;
    set isTrackPending(newValue: boolean);
    get isRunning(): boolean;
    set isRunning(newValue: boolean);
    get diffValue(): 0 | 1;
    set diffValue(newValue: 0 | 1);
    onBecomeStale_(): void;
    schedule_(): void;
    /**
     * internal, use schedule() if you intend to kick off a reaction
     */
    runReaction_(): void;
    track(fn: () => void): void;
    reportExceptionInDerivation_(error: any): void;
    dispose(): void;
    getDisposer_(abortSignal?: GenericAbortSignal): IReactionDisposer;
    toString(): string;
}
declare function onReactionError(handler: (error: any, derivation: IDerivation) => void): Lambda;

type IObjectDidChange<T = any> = {
    observableKind: "object";
    name: PropertyKey;
    object: T;
    debugObjectName: string;
} & ({
    type: "add";
    newValue: any;
} | {
    type: "update";
    oldValue: any;
    newValue: any;
} | {
    type: "remove";
    oldValue: any;
});
type IObjectWillChange<T = any> = {
    object: T;
    type: "update" | "add";
    name: PropertyKey;
    newValue: any;
} | {
    object: T;
    type: "remove";
    name: PropertyKey;
};
declare class ObservableObjectAdministration implements IInterceptable<IObjectWillChange>, IListenable {
    target_: any;
    values_: Map<PropertyKey, ComputedValue<any> | ObservableValue<any>>;
    name_: string;
    defaultAnnotation_: Annotation;
    keysAtom_: IAtom;
    changeListeners_: any;
    interceptors_: any;
    proxy_: any;
    isPlainObject_: boolean;
    appliedAnnotations_?: object;
    private pendingKeys_;
    lazyComputedKeys_: undefined | Map<PropertyKey, () => ComputedValue<any>>;
    lazyObservableKeys_: undefined | Map<PropertyKey, () => ObservableValue<any>>;
    constructor(target_: any, values_: Map<PropertyKey, ComputedValue<any> | ObservableValue<any>> | undefined, name_: string, defaultAnnotation_?: Annotation);
    getObservablePropValue_(key: PropertyKey): any;
    materializeLazyComputed_(key: PropertyKey): ComputedValue<any> | undefined;
    materializeLazyObservable_(key: PropertyKey): ObservableValue<any> | undefined;
    setObservablePropValue_(key: PropertyKey, newValue: any): boolean | null;
    get_(key: PropertyKey): any;
    /**
     * @param {PropertyKey} key
     * @param {any} value
     * @param {Annotation|boolean} annotation true - use default annotation, false - copy as is
     * @param {boolean} proxyTrap whether it's called from proxy trap
     * @returns {boolean|null} true on success, false on failure (proxyTrap + non-configurable), null when cancelled by interceptor
     */
    set_(key: PropertyKey, value: any, proxyTrap?: boolean): boolean | null;
    has_(key: PropertyKey): boolean;
    /**
     * @param {PropertyKey} key
     * @param {PropertyDescriptor} descriptor
     * @param {Annotation|boolean} annotation true - use default annotation, false - copy as is
     * @param {boolean} proxyTrap whether it's called from proxy trap
     * @returns {boolean|null} true on success, false on failure (proxyTrap + non-configurable), null when cancelled by interceptor
     */
    extend_(key: PropertyKey, descriptor: PropertyDescriptor, annotation: Annotation | boolean, proxyTrap?: boolean): boolean | null;
    /**
     * @param {PropertyKey} key
     * @param {PropertyDescriptor} descriptor
     * @param {boolean} proxyTrap whether it's called from proxy trap
     * @returns {boolean|null} true on success, false on failure (proxyTrap + non-configurable), null when cancelled by interceptor
     */
    defineProperty_(key: PropertyKey, descriptor: PropertyDescriptor, proxyTrap?: boolean): boolean | null;
    defineObservableProperty_(key: PropertyKey, value: any, enhancer: IEnhancer<any>, proxyTrap?: boolean): boolean | null;
    defineComputedProperty_(key: PropertyKey, options: IComputedValueOptions<any>, proxyTrap?: boolean): boolean | null;
    /**
     * @param {PropertyKey} key
     * @param {PropertyDescriptor} descriptor
     * @param {boolean} proxyTrap whether it's called from proxy trap
     * @returns {boolean|null} true on success, false on failure (proxyTrap + non-configurable), null when cancelled by interceptor
     */
    delete_(key: PropertyKey, proxyTrap?: boolean): boolean | null;
    notifyPropertyAddition_(key: PropertyKey, value: any): void;
    ownKeys_(): Array<string | symbol>;
    keys_(): PropertyKey[];
}
declare function isObservableObject(thing: any): boolean;

interface IObservableArray<T = any> extends Array<T> {
    spliceWithArray(index: number, deleteCount?: number, newItems?: T[]): T[];
    clear(): T[];
    replace(newItems: T[]): T[];
    remove(value: T): boolean;
    toJSON(): T[];
}
interface IArrayBaseChange<T> {
    object: IObservableArray<T>;
    observableKind: "array";
    debugObjectName: string;
    index: number;
}
type IArrayDidChange<T = any> = IArrayUpdate<T> | IArraySplice<T>;
interface IArrayUpdate<T = any> extends IArrayBaseChange<T> {
    type: "update";
    newValue: T;
    oldValue: T;
}
interface IArraySplice<T = any> extends IArrayBaseChange<T> {
    type: "splice";
    added: T[];
    addedCount: number;
    removed: T[];
    removedCount: number;
}
interface IArrayWillChange<T = any> {
    object: IObservableArray<T>;
    index: number;
    type: "update";
    newValue: T;
}
interface IArrayWillSplice<T = any> {
    object: IObservableArray<T>;
    index: number;
    type: "splice";
    added: T[];
    removedCount: number;
}
declare function isObservableArray(thing: any): thing is IObservableArray<any>;

type PureSpyEvent = {
    type: "action";
    name: string;
    object: unknown;
    arguments: unknown[];
} | {
    type: "scheduled-reaction";
    name: string;
} | {
    type: "reaction";
    name: string;
} | {
    type: "error";
    name: string;
    message: string;
    error: string;
} | IComputedDidChange<unknown> | IObjectDidChange<unknown> | IArrayDidChange<unknown> | IMapDidChange<unknown, unknown> | ISetDidChange<unknown> | IValueDidChange<unknown> | IBoxDidChange<unknown> | {
    type: "report-end";
    spyReportEnd: true;
    time?: number;
};
type SpyEvent = PureSpyEvent & {
    spyReportStart?: true;
};
declare function spy(listener: (change: SpyEvent) => void): Lambda;

interface IActionFactory extends Annotation, ClassMethodAndFieldDecorator {
    <T extends Function | undefined | null>(fn: T): T;
    <T extends Function | undefined | null>(name: string, fn: T): T;
    (customName: string): DecoratorAnnotation<ClassMethodAndFieldDecorator>;
}
declare const action: IActionFactory;
declare const autoAction: IActionFactory;
declare const actionBound: DecoratorAnnotation<ClassMethodAndFieldDecorator>;
declare const autoActionBound: DecoratorAnnotation<ClassMethodAndFieldDecorator>;
declare function runInAction<T>(fn: () => T): T;
declare function isAction(thing: any): boolean;

interface IAutorunOptions {
    delay?: number;
    name?: string;
    /**
     * Experimental.
     * Warns if the view doesn't track observables
     */
    requiresObservable?: boolean;
    scheduler?: (callback: () => void) => any;
    onError?: (error: any) => void;
    signal?: GenericAbortSignal;
}
/**
 * Creates a named reactive view and keeps it alive, so that the view is always
 * updated if one of the dependencies changes, even when the view is not further used by something else.
 * @param view The reactive view
 * @returns disposer function, which can be used to stop the view from being updated in the future.
 */
declare function autorun(view: (r: IReactionPublic) => any, opts?: IAutorunOptions): IReactionDisposer;
type IReactionOptions<T, FireImmediately extends boolean> = IAutorunOptions & {
    fireImmediately?: FireImmediately;
    equals?: IEqualsComparer<T>;
};
declare function reaction<T, FireImmediately extends boolean = false>(expression: (r: IReactionPublic) => T, effect: (arg: T, prev: FireImmediately extends true ? T | undefined : T, r: IReactionPublic) => void, opts?: IReactionOptions<T, FireImmediately>): IReactionDisposer;

declare function onBecomeObserved(value: IObservable | IComputedValue<any> | IObservableArray<any> | ObservableMap<any, any> | ObservableSet<any> | IObservableValue<any>, listener: Lambda): Lambda;
declare function onBecomeObserved<K, V = any>(value: ObservableMap<K, V> | Object, property: K, listener: Lambda): Lambda;
declare function onBecomeUnobserved(value: IObservable | IComputedValue<any> | IObservableArray<any> | ObservableMap<any, any> | ObservableSet<any> | IObservableValue<any>, listener: Lambda): Lambda;
declare function onBecomeUnobserved<K, V = any>(value: ObservableMap<K, V> | Object, property: K, listener: Lambda): Lambda;

declare function configure(options: {
    enforceActions?: "never" | "always" | "observed";
    computedRequiresReaction?: boolean;
    /**
     * Warn if you try to create to derivation / reactive context without accessing any observable.
     */
    reactionRequiresObservable?: boolean;
    /**
     * Warn if observables are accessed outside a reactive context
     */
    observableRequiresReaction?: boolean;
    isolateGlobalState?: boolean;
    disableErrorBoundaries?: boolean;
    safeDescriptors?: boolean;
    reactionScheduler?: (f: () => void) => void;
}): void;

declare function extendObservable<A extends Object, B extends Object>(target: A, properties: B, annotations?: AnnotationsMap<B, never>, options?: CreateObservableOptions): A & B;

interface IDependencyTree {
    name: string;
    dependencies?: IDependencyTree[];
}
interface IObserverTree {
    name: string;
    observers?: IObserverTree[];
}
declare function getDependencyTree(thing: any, property?: string): IDependencyTree;
declare function getObserverTree(thing: any, property?: string): IObserverTree;

declare class FlowCancellationError extends Error {
    constructor();
    toString(): string;
}
declare function isFlowCancellationError(error: Error): error is FlowCancellationError;
type CancellablePromise<T> = Promise<T> & {
    cancel(): void;
};
interface Flow extends Annotation, ClassMethodDecorator {
    <R, Args extends any[]>(generator: (...args: Args) => Generator<any, R, any> | AsyncGenerator<any, R, any>, context?: never): (...args: Args) => CancellablePromise<R>;
}
declare const flow: Flow;
declare const flowBound: DecoratorAnnotation<ClassMethodDecorator>;
declare function flowResult<T>(result: T): T extends Generator<any, infer R, any> ? CancellablePromise<R> : T extends CancellablePromise<any> ? T : never;
declare function isFlow(fn: any): boolean;

type ReadInterceptor<T> = (value: any) => T;
/** Experimental feature right now, tested indirectly via Mobx-State-Tree */
declare function interceptReads<T>(value: IObservableValue<T>, handler: ReadInterceptor<T>): Lambda;
declare function interceptReads<T>(observableArray: IObservableArray<T>, handler: ReadInterceptor<T>): Lambda;
declare function interceptReads<K, V>(observableMap: ObservableMap<K, V>, handler: ReadInterceptor<V>): Lambda;
declare function interceptReads<V>(observableSet: ObservableSet<V>, handler: ReadInterceptor<V>): Lambda;
declare function interceptReads(object: Object, property: string, handler: ReadInterceptor<any>): Lambda;

declare function intercept<T>(value: IObservableValue<T>, handler: IInterceptor<IValueWillChange<T>>): Lambda;
declare function intercept<T>(observableArray: IObservableArray<T> | Array<T>, handler: IInterceptor<IArrayWillChange<T> | IArrayWillSplice<T>>): Lambda;
declare function intercept<K, V>(observableMap: ObservableMap<K, V> | Map<K, V>, handler: IInterceptor<IMapWillChange<K, V>>): Lambda;
declare function intercept<V>(observableSet: ObservableSet<V> | Set<V>, handler: IInterceptor<ISetWillChange<V>>): Lambda;
declare function intercept<K, V>(observableMap: ObservableMap<K, V> | Map<K, V>, property: K, handler: IInterceptor<IValueWillChange<V>>): Lambda;
declare function intercept(object: object, handler: IInterceptor<IObjectWillChange>): Lambda;
declare function intercept<T extends object, K extends keyof T>(object: T, property: K, handler: IInterceptor<IValueWillChange<T[K]>>): Lambda;

declare function isComputed(value: any): boolean;
declare function isComputedProp(value: any, propName: PropertyKey): boolean;

declare function isObservable(value: any): boolean;
declare function isObservableProp(value: any, propName: PropertyKey): boolean;

declare function keys<K>(map: ObservableMap<K, any>): ReadonlyArray<K>;
declare function keys<T>(ar: IObservableArray<T>): ReadonlyArray<number>;
declare function keys<T>(set: ObservableSet<T>): ReadonlyArray<T>;
declare function keys<T extends Object>(obj: T): ReadonlyArray<PropertyKey>;
declare function values<K, T>(map: ObservableMap<K, T>): ReadonlyArray<T>;
declare function values<T>(set: ObservableSet<T>): ReadonlyArray<T>;
declare function values<T>(ar: IObservableArray<T>): ReadonlyArray<T>;
declare function values<T = any>(obj: T): ReadonlyArray<T extends object ? T[keyof T] : any>;
declare function entries<K, T>(map: ObservableMap<K, T>): ReadonlyArray<[K, T]>;
declare function entries<T>(set: ObservableSet<T>): ReadonlyArray<[T, T]>;
declare function entries<T>(ar: IObservableArray<T>): ReadonlyArray<[number, T]>;
declare function entries<T = any>(obj: T): ReadonlyArray<[string, T extends object ? T[keyof T] : any]>;
declare function set<V>(obj: ObservableMap<PropertyKey, V>, values: {
    [key: string]: V;
}): any;
declare function set<K, V>(obj: ObservableMap<K, V>, key: K, value: V): any;
declare function set<T>(obj: ObservableSet<T>, value: T): any;
declare function set<T>(obj: IObservableArray<T>, index: number, value: T): any;
declare function set<T extends Object>(obj: T, values: {
    [key: string]: any;
}): any;
declare function set<T extends Object>(obj: T, key: PropertyKey, value: any): any;
declare function remove<K, V>(obj: ObservableMap<K, V>, key: K): any;
declare function remove<T>(obj: ObservableSet<T>, key: T): any;
declare function remove<T>(obj: IObservableArray<T>, index: number): any;
declare function remove<T extends Object>(obj: T, key: string): any;
declare function has<K>(obj: ObservableMap<K, any>, key: K): boolean;
declare function has<T>(obj: ObservableSet<T>, key: T): boolean;
declare function has<T>(obj: IObservableArray<T>, index: number): boolean;
declare function has<T extends Object>(obj: T, key: string): boolean;
declare function get<K, V>(obj: ObservableMap<K, V>, key: K): V | undefined;
declare function get<T>(obj: IObservableArray<T>, index: number): T | undefined;
declare function get<T extends Object>(obj: T, key: string): any;
declare function apiDefineProperty(obj: Object, key: PropertyKey, descriptor: PropertyDescriptor): boolean | null;
declare function apiOwnKeys(obj: Object): (string | symbol)[];

declare function observe<T>(value: IObservableValue<T> | IComputedValue<T>, listener: (change: IValueDidChange<T>) => void, fireImmediately?: boolean): Lambda;
declare function observe<T>(observableArray: IObservableArray<T> | Array<T>, listener: (change: IArrayDidChange<T>) => void, fireImmediately?: boolean): Lambda;
declare function observe<V>(observableSet: ObservableSet<V> | Set<V>, listener: (change: ISetDidChange<V>) => void, fireImmediately?: boolean): Lambda;
declare function observe<K, V>(observableMap: ObservableMap<K, V> | Map<K, V>, listener: (change: IMapDidChange<K, V>) => void, fireImmediately?: boolean): Lambda;
declare function observe<K, V>(observableMap: ObservableMap<K, V> | Map<K, V>, property: K, listener: (change: IValueDidChange<V>) => void, fireImmediately?: boolean): Lambda;
declare function observe(object: Object, listener: (change: IObjectDidChange) => void, fireImmediately?: boolean): Lambda;
declare function observe<T, K extends keyof T>(object: T, property: K, listener: (change: IValueDidChange<T[K]>) => void, fireImmediately?: boolean): Lambda;

/**
 * Recursively converts an observable to it's non-observable native counterpart.
 * It does NOT recurse into non-observables, these are left as they are, even if they contain observables.
 * Computed and other non-enumerable properties are completely ignored.
 * Complex scenarios require custom solution, eg implementing `toJSON` or using `serializr` lib.
 */
declare function toJS<T>(source: T, options?: any): T;

/**
 * During a transaction no views are updated until the end of the transaction.
 * The transaction will be run synchronously nonetheless.
 *
 * @param action a function that updates some reactive state
 * @returns any value that was returned by the 'action' parameter.
 */
declare function transaction<T>(action: () => T, thisArg?: undefined): T;

interface IWhenOptions {
    name?: string;
    timeout?: number;
    onError?: (error: any) => void;
    signal?: GenericAbortSignal;
}
declare function when(predicate: () => boolean, opts?: IWhenOptions): Promise<void> & {
    cancel(): void;
};
declare function when(predicate: () => boolean, effect: Lambda, opts?: IWhenOptions): IReactionDisposer;

type IInterceptor<T> = (change: T) => T | null;
interface IInterceptable<T> {
    interceptors_: IInterceptor<T>[] | undefined;
}

interface IListenable {
    changeListeners_: Function[] | undefined;
}

type NoInfer<T> = [T][T extends any ? 0 : never];
declare function makeObservable<T extends object, AdditionalKeys extends PropertyKey = never>(target: T, annotations: AnnotationsMap<T, NoInfer<AdditionalKeys>>, options?: CreateObservableOptions): T;
declare function makeAutoObservable<T extends object, AdditionalKeys extends PropertyKey = never>(target: T, overrides?: AnnotationsMap<T, NoInfer<AdditionalKeys>>, options?: CreateObservableOptions): T;

interface IKeyValueMap<V = any> {
    [key: string]: V;
}
type IMapEntry<K = any, V = any> = [K, V];
type IReadonlyMapEntry<K = any, V = any> = readonly [K, V];
type IMapEntries<K = any, V = any> = IMapEntry<K, V>[];
type IReadonlyMapEntries<K = any, V = any> = readonly IReadonlyMapEntry<K, V>[];
type IMapDidChange<K = any, V = any> = {
    observableKind: "map";
    debugObjectName: string;
} & ({
    object: ObservableMap<K, V>;
    name: K;
    type: "update";
    newValue: V;
    oldValue: V;
} | {
    object: ObservableMap<K, V>;
    name: K;
    type: "add";
    newValue: V;
} | {
    object: ObservableMap<K, V>;
    name: K;
    type: "delete";
    oldValue: V;
});
interface IMapWillChange<K = any, V = any> {
    object: ObservableMap<K, V>;
    type: "update" | "add" | "delete";
    name: K;
    newValue?: V;
}
type IObservableMapInitialValues<K = any, V = any> = IMapEntries<K, V> | IReadonlyMapEntries<K, V> | IKeyValueMap<V> | Map<K, V>;
declare class ObservableMap<K = any, V = any> implements Map<K, V>, IInterceptable<IMapWillChange<K, V>>, IListenable {
    enhancer_: IEnhancer<V>;
    name_: string;
    [$mobx]: {};
    data_: Map<K, ObservableValue<V>>;
    hasMap_: Map<K, ObservableValue<boolean>>;
    keysAtom_: IAtom;
    interceptors_: any;
    changeListeners_: any;
    dehancer: any;
    constructor(initialData?: IObservableMapInitialValues<K, V>, enhancer_?: IEnhancer<V>, name_?: string);
    private has_;
    has(key: K): boolean;
    set(key: K, value: V): this;
    delete(key: K): boolean;
    private updateValue_;
    private addValue_;
    get(key: K): V | undefined;
    getOrInsert(key: K, value: V): V;
    getOrInsertComputed(key: K, callback: (key: K) => V): V;
    private dehanceValue_;
    keys(): MapIterator<K>;
    values(): MapIterator<V>;
    entries(): MapIterator<IMapEntry<K, V>>;
    [Symbol.iterator](): MapIterator<IMapEntry<K, V>>;
    forEach(callback: (value: V, key: K, object: Map<K, V>) => void, thisArg?: any): void;
    /** Merge another object into this object, returns this. */
    merge(other?: IObservableMapInitialValues<K, V>): ObservableMap<K, V>;
    clear(): void;
    replace(values: IObservableMapInitialValues<K, V>): ObservableMap<K, V>;
    get size(): number;
    toString(): string;
    toJSON(): [K, V][];
    get [Symbol.toStringTag](): string;
}
declare var isObservableMap: (thing: any) => thing is ObservableMap<any, any>;

type IObservableSetInitialValues<T> = Set<T> | readonly T[];
type ISetDidChange<T = any> = {
    object: ObservableSet<T>;
    observableKind: "set";
    debugObjectName: string;
    type: "add";
    newValue: T;
} | {
    object: ObservableSet<T>;
    observableKind: "set";
    debugObjectName: string;
    type: "delete";
    oldValue: T;
};
type ISetWillDeleteChange<T = any> = {
    type: "delete";
    object: ObservableSet<T>;
    oldValue: T;
};
type ISetWillAddChange<T = any> = {
    type: "add";
    object: ObservableSet<T>;
    newValue: T;
};
type ISetWillChange<T = any> = ISetWillDeleteChange<T> | ISetWillAddChange<T>;
declare class ObservableSet<T = any> implements Set<T>, IInterceptable<ISetWillChange>, IListenable {
    name_: string;
    [$mobx]: {};
    private data_;
    atom_: IAtom;
    changeListeners_: any;
    interceptors_: any;
    dehancer: any;
    enhancer_: (newV: any, oldV: any | undefined) => any;
    constructor(initialData?: IObservableSetInitialValues<T>, enhancer?: IEnhancer<T>, name_?: string);
    private dehanceValue_;
    clear(): void;
    forEach(callbackFn: (value: T, value2: T, set: Set<T>) => void, thisArg?: any): void;
    get size(): number;
    add(value: T): this;
    delete(value: T): boolean;
    has(value: T): boolean;
    entries(): SetIterator<[T, T]>;
    keys(): SetIterator<T>;
    values(): SetIterator<T>;
    intersection<U>(otherSet: ReadonlySetLike<U> | Set<U>): Set<T & U>;
    union<U>(otherSet: ReadonlySetLike<U> | Set<U>): Set<T | U>;
    difference<U>(otherSet: ReadonlySetLike<U>): Set<T>;
    symmetricDifference<U>(otherSet: ReadonlySetLike<U> | Set<U>): Set<T | U>;
    isSubsetOf(otherSet: ReadonlySetLike<unknown>): boolean;
    isSupersetOf(otherSet: ReadonlySetLike<unknown>): boolean;
    isDisjointFrom(otherSet: ReadonlySetLike<unknown> | Set<unknown>): boolean;
    replace(other: ObservableSet<T> | IObservableSetInitialValues<T>): ObservableSet<T>;
    toJSON(): T[];
    toString(): string;
    [Symbol.iterator](): SetIterator<T>;
    get [Symbol.toStringTag](): string;
}
declare var isObservableSet: (thing: any) => thing is ObservableSet<any>;

declare function getAtom(thing: any, property?: PropertyKey): IDepTreeNode;
declare function getAdministration(thing: any, property?: string): any;
declare function getDebugName(thing: any, property?: string): string;

export { $mobx, FlowCancellationError, ObservableMap, ObservableSet, Reaction, allowStateChanges as _allowStateChanges, runInAction as _allowStateChangesInsideComputed, allowStateReadsEnd as _allowStateReadsEnd, allowStateReadsStart as _allowStateReadsStart, autoAction as _autoAction, autoActionBound as _autoActionBound, _endAction, getAdministration as _getAdministration, getGlobalState as _getGlobalState, interceptReads as _interceptReads, isComputingDerivation as _isComputingDerivation, resetGlobalState as _resetGlobalState, _startAction, action, actionBound, autorun, compareDefault, compareIdentity, compareShallow, compareStructural, computed, computedStruct, configure, createAtom, apiDefineProperty as defineProperty, entries, extendObservable, flow, flowBound, flowResult, get, getAtom, getDebugName, getDependencyTree, getObserverTree, has, intercept, isAction, isObservableValue as isBoxedObservable, isComputed, isComputedProp, isFlow, isFlowCancellationError, isObservable, isObservableArray, isObservableMap, isObservableObject, isObservableProp, isObservableSet, keys, makeAutoObservable, makeObservable, observable, observableDeep, observableRef, observableShallow, observableStruct, observe, onBecomeObserved, onBecomeUnobserved, onReactionError, override, apiOwnKeys as ownKeys, reaction, remove, runInAction, set, spy, toJS, transaction, untracked, values, when };
export type { AnnotationMapEntry, AnnotationsMap, CancellablePromise, CreateObservableOptions, IActionFactory, IActionRunInfo, IArrayDidChange, IArraySplice, IArrayUpdate, IArrayWillChange, IArrayWillSplice, IAtom, IAutorunOptions, IComputedFactory, IComputedValue, IComputedValueOptions, IDepTreeNode, IDependencyTree, IEnhancer, IEqualsComparer, IInterceptable, IInterceptor, IKeyValueMap, IListenable, IMapDidChange, IMapEntries, IMapEntry, IMapWillChange, IObjectDidChange, IObjectWillChange, IObservable, IObservableArray, IObservableFactory, IObservableMapInitialValues, IObservableSetInitialValues, IObservableValue, IObserverTree, IReactionDisposer, IReactionOptions, IReactionPublic, ISetDidChange, ISetWillChange, IValueDidChange, IValueWillChange, IWhenOptions, Lambda };
