/* languages0.9.6.12.js
   Hard coded languages supported by translate-shell 0.9.6.12
   This is the current version in Ubuntu/Mint repositories
*/

const hardcodedLanguages = [
   {code:"af",      englishName:"Afrikaans"},
   {code:"he",      englishName:"Hebrew"},
   {code:"pt",      englishName:"Portuguese"},
   {code:"sq",      englishName:"Albanian"},
   {code:"mrj",     englishName:"Hill Mari"},
   {code:"pa",      englishName:"Punjabi"},
   {code:"am",      englishName:"Amharic"},
   {code:"hi",      englishName:"Hindi"},
   {code:"otq",     englishName:"Querétaro Otomi"},
   {code:"ar",      englishName:"Arabic"},
   {code:"hmn",     englishName:"Hmong"},
   {code:"ro",      englishName:"Romanian"},
   {code:"hy",      englishName:"Armenian"},
   {code:"mww",     englishName:"Hmong Daw"},
   {code:"ru",      englishName:"Russian"},
   {code:"az",      englishName:"Azerbaijani"},
   {code:"hu",      englishName:"Hungarian"},
   {code:"sm",      englishName:"Samoan"},
   {code:"ba",      englishName:"Bashkir"},
   {code:"is",      englishName:"Icelandic"},
   {code:"gd",      englishName:"Scots Gaelic"},
   {code:"eu",      englishName:"Basque"},
   {code:"ig",      englishName:"Igbo"},
   {code:"sr-Cyrl", englishName:"Serbian (Cyrillic)"},
   {code:"be",      englishName:"Belarusian"},
   {code:"id",      englishName:"Indonesian"},
   {code:"sr-Latn", englishName:"Serbian (Latin)"},
   {code:"bn",      englishName:"Bengali"},
   {code:"ga",      englishName:"Irish"},
   {code:"st",      englishName:"Sesotho"},
   {code:"bs",      englishName:"Bosnian"},
   {code:"it",      englishName:"Italian"},
   {code:"sn",      englishName:"Shona"},
   {code:"bg",      englishName:"Bulgarian"},
   {code:"ja",      englishName:"Japanese"},
   {code:"sd",      englishName:"Sindhi"},
   {code:"yue",     englishName:"Cantonese"},
   {code:"jv",      englishName:"Javanese"},
   {code:"si",      englishName:"Sinhala"},
   {code:"ca",      englishName:"Catalan"},
   {code:"kn",      englishName:"Kannada"},
   {code:"sk",      englishName:"Slovak"},
   {code:"ceb",     englishName:"Cebuano"},
   {code:"kk",      englishName:"Kazakh"},
   {code:"sl",      englishName:"Slovenian"},
   {code:"ny",      englishName:"Chichewa"},
   {code:"km",      englishName:"Khmer"},
   {code:"so",      englishName:"Somali"},
   {code:"zh-CN",   englishName:"Chinese Simplified"},
   {code:"tlh",     englishName:"Klingon"},
   {code:"es",      englishName:"Spanish"},
   {code:"zh-TW",   englishName:"Chinese Traditional"},
   {code:"tlh-Qaak", englishName:"Klingon (pIqaD)"},
   {code:"su",      englishName:"Sundanese"},
   {code:"co",      englishName:"Corsican"},
   {code:"ko",      englishName:"Korean"},
   {code:"sw",      englishName:"Swahili"},
   {code:"hr",      englishName:"Croatian"},
   {code:"ku",      englishName:"Kurdish"},
   {code:"sv",      englishName:"Swedish"},
   {code:"cs",      englishName:"Czech"},
   {code:"ky",      englishName:"Kyrgyz"},
   {code:"ty",      englishName:"Tahitian"},
   {code:"da",      englishName:"Danish"},
   {code:"lo",      englishName:"Lao"},
   {code:"tg",      englishName:"Tajik"},
   {code:"nl",      englishName:"Dutch"},
   {code:"la",      englishName:"Latin"},
   {code:"ta",      englishName:"Tamil"},
   {code:"mhr",     englishName:"Eastern Mari"},
   {code:"lv",      englishName:"Latvian"},
   {code:"tt",      englishName:"Tatar"},
   {code:"emj",     englishName:"Emoji"},
   {code:"lt",      englishName:"Lithuanian"},
   {code:"te",      englishName:"Telugu"},
   {code:"en",      englishName:"English"},
   {code:"lb",      englishName:"Luxembourgish"},
   {code:"th",      englishName:"Thai"},
   {code:"eo",      englishName:"Esperanto"},
   {code:"mk",      englishName:"Macedonian"},
   {code:"to",      englishName:"Tongan"},
   {code:"et",      englishName:"Estonian"},
   {code:"mg",      englishName:"Malagasy"},
   {code:"tr",      englishName:"Turkish"},
   {code:"fj",      englishName:"Fijian"},
   {code:"ms",      englishName:"Malay"},
   {code:"udm",     englishName:"Udmurt"},
   {code:"tl",      englishName:"Filipino"},
   {code:"ml",      englishName:"Malayalam"},
   {code:"uk",      englishName:"Ukrainian"},
   {code:"fi",      englishName:"Finnish"},
   {code:"mt",      englishName:"Maltese"},
   {code:"ur",      englishName:"Urdu"},
   {code:"fr",      englishName:"French"},
   {code:"mi",      englishName:"Maori"},
   {code:"uz",      englishName:"Uzbek"},
   {code:"fy",      englishName:"Frisian"},
   {code:"mr",      englishName:"Marathi"},
   {code:"vi",      englishName:"Vietnamese"},
   {code:"gl",      englishName:"Galician"},
   {code:"mn",      englishName:"Mongolian"},
   {code:"cy",      englishName:"Welsh"},
   {code:"ka",      englishName:"Georgian"},
   {code:"my",      englishName:"Myanmar"},
   {code:"xh",      englishName:"Xhosa"},
   {code:"de",      englishName:"German"},
   {code:"ne",      englishName:"Nepali"},
   {code:"yi",      englishName:"Yiddish"},
   {code:"el",      englishName:"Greek"},
   {code:"no",      englishName:"Norwegian"},
   {code:"yo",      englishName:"Yoruba"},
   {code:"gu",      englishName:"Gujarati"},
   {code:"pap",     englishName:"Papiamento"},
   {code:"yua",     englishName:"Yucatec Maya"},
   {code:"ht",      englishName:"Haitian Creole"},
   {code:"ps",      englishName:"Pashto"},
   {code:"zu",      englishName:"Zulu"},
   {code:"ha",      englishName:"Hausa"},
   {code:"fa",      englishName:"Persian"},
   {code:"haw",     englishName:"Hawaiian"},
   {code:"pl",      englishName:"Polish"}
]

exports.hardcodedLanguages = hardcodedLanguages