/* languages0.9.6.12.js
   Hard coded languages supported by translate-shell 0.9.6.12
   This is the current version in Ubuntu/Mint repositories
*/

const hardcodedLanguages = [
   {code:"af",      englishName:"Afrikaans",            name: "Afrikaans"},
   {code:"sq",      englishName:"Albanian",             name: "Shqip"},
   {code:"am",      englishName:"Amharic",              name: "አማርኛ"},
   {code:"ar",      englishName:"Arabic",               name: "ﺔﻴﺑﺮﻌﻟﺍ"},
   {code:"hy",      englishName:"Armenian",             name: "Հայերեն"},
   {code:"az",      englishName:"Azerbaijani",          name: "Azərbaycanca"},
   {code:"ba",      englishName:"Bashkir",              name: "Башҡортса"},
   {code:"eu",      englishName:"Basque",               name: "Euskara"},
   {code:"be",      englishName:"Belarusian",           name: "беларуская"},
   {code:"bn",      englishName:"Bengali",              name: "বাংলা"},
   {code:"bs",      englishName:"Bosnian",              name: "Bosanski"},
   {code:"bg",      englishName:"Bulgarian",            name: "български"},
   {code:"yue",     englishName:"Cantonese",            name: "粵語"},
   {code:"ca",      englishName:"Catalan",              name: "Català"},
   {code:"ceb",     englishName:"Cebuano",              name: "Cebuano"},
   {code:"ny",      englishName:"Chichewa",             name: "Nyanja"},
   {code:"zh-CN",   englishName:"Chinese Simplified",   name: "简体中文"},
   {code:"zh-TW",   englishName:"Chinese Traditional",  name: "繁體中文"},
   {code:"co",      englishName:"Corsican",             name: "Corsu"},
   {code:"hr",      englishName:"Croatian",             name: "Hrvatski"},
   {code:"cs",      englishName:"Czech",                name: "Čeština"},
   {code:"da",      englishName:"Danish",               name: "Dansk"},
   {code:"nl",      englishName:"Dutch",                name: "Nederlands"},
   {code:"mhr",     englishName:"Eastern Mari",         name: "Олык марий"},
   {code:"emj",     englishName:"Emoji",                name: "Emoji"},
   {code:"en",      englishName:"English",              name: "English"},
   {code:"eo",      englishName:"Esperanto",            name: "Esperanto"},
   {code:"et",      englishName:"Estonian",             name: "Eesti"},
   {code:"fj",      englishName:"Fijian",               name: "Vosa Vakaviti"},
   {code:"tl",      englishName:"Filipino",             name: "Filipino"},
   {code:"fi",      englishName:"Finnish",              name: "Suomi"},
   {code:"fr",      englishName:"French",               name: "Français"},
   {code:"fy",      englishName:"Frisian",              name: "Frysk"},
   {code:"gl",      englishName:"Galician",             name: "Galego"},
   {code:"ka",      englishName:"Georgian",             name: "ქართული"},
   {code:"de",      englishName:"German",               name: "Deutsch"},
   {code:"el",      englishName:"Greek",                name: "Ελληνικά"},
   {code:"gu",      englishName:"Gujarati",             name: "ગુજરાતી"},
   {code:"ht",      englishName:"Haitian Creole",       name: "Kreyòl Ayisyen"},
   {code:"ha",      englishName:"Hausa",                name: "Hausa"},
   {code:"haw",     englishName:"Hawaiian",             name: "ʻŌlelo Hawaiʻi"},
   {code:"he",      englishName:"Hebrew",               name: "תירִבְעִ"},
   {code:"mrj",     englishName:"Hill Mari",            name: "Кырык мары"},
   {code:"hi",      englishName:"Hindi",                name: "हिन्दी"},
   {code:"mww",     englishName:"Hmong Daw",            name: "Hmoob"},
   {code:"hmn",     englishName:"Hmong",                name: "Hmoob"},
   {code:"hu",      englishName:"Hungarian",            name: "Magyar"},
   {code:"is",      englishName:"Icelandic",            name: "Íslenska"},
   {code:"ig",      englishName:"Igbo",                 name: "Igbo"},
   {code:"id",      englishName:"Indonesian",           name: "Bahasa Indonesia"},
   {code:"ga",      englishName:"Irish",                name: "Gaeilge"},
   {code:"it",      englishName:"Italian",              name: "Italiano"},
   {code:"ja",      englishName:"Japanese",             name: "日本語"},
   {code:"jv",      englishName:"Javanese",             name: "Basa Jawa"},
   {code:"kn",      englishName:"Kannada",              name: "ಕನ್ನಡ"},
   {code:"kk",      englishName:"Kazakh",               name: "Қазақ тілі"},
   {code:"km",      englishName:"Khmer",                name: "ភាសាខ្មែរ"},
   {code:"tlh",     englishName:"Klingon",              name: "tlhIngan Hol"},
   {code:"tlh-Qaak", englishName:"Klingon (pIqaD)",     name: "Klingon"},
   {code:"ko",      englishName:"Korean",               name: "한국어"},
   {code:"ku",      englishName:"Kurdish",              name: "Kurmancî"},
   {code:"ky",      englishName:"Kyrgyz",               name: "Кыргызча"},
   {code:"lo",      englishName:"Lao",                  name: "ລາວ"},
   {code:"la",      englishName:"Latin",                name: "Latina"},
   {code:"lv",      englishName:"Latvian",              name: "Latviešu"},
   {code:"lt",      englishName:"Lithuanian",           name: "Lietuvių"},
   {code:"lb",      englishName:"Luxembourgish",        name: "Lëtzebuergesch"},
   {code:"mk",      englishName:"Macedonian",           name: "Македонски"},
   {code:"mg",      englishName:"Malagasy",             name: "Malagasy"},
   {code:"ms",      englishName:"Malay",                name: "Bahasa Melayu"},
   {code:"ml",      englishName:"Malayalam",            name: "മലയാളം"},
   {code:"mt",      englishName:"Maltese",              name: "Malti"},
   {code:"mi",      englishName:"Maori",                name: "Māori"},
   {code:"mr",      englishName:"Marathi",              name: "मराठी"},
   {code:"mn",      englishName:"Mongolian",            name: "Монгол"},
   {code:"my",      englishName:"Myanmar",              name: "မြန်မာစာ"},
   {code:"ne",      englishName:"Nepali",               name: "नेपाली"},
   {code:"no",      englishName:"Norwegian",            name: "Norsk"},
   {code:"pap",     englishName:"Papiamento",           name: "Papiamentu"},
   {code:"ps",      englishName:"Pashto",               name: "ﻮﺘښﭘ"},
   {code:"fa",      englishName:"Persian",              name: "ﯽﺳﺭﺎﻓ"},
   {code:"pl",      englishName:"Polish",               name: "Polski"},
   {code:"pt",      englishName:"Portuguese",           name: "Português"},
   {code:"pa",      englishName:"Punjabi",              name: "ਪੰਜਾਬੀ"},
   {code:"otq",     englishName:"Querétaro Otomi",      name: "Hñąñho"},
   {code:"ro",      englishName:"Romanian",             name: "Română"},
   {code:"ru",      englishName:"Russian",              name: "Русский"},
   {code:"sm",      englishName:"Samoan",               name: "Gagana Sāmoa"},
   {code:"gd",      englishName:"Scots Gaelic",         name: "Gàidhlig"},
   {code:"sr-Cyrl", englishName:"Serbian (Cyrillic)",   name: "Српски"},
   {code:"sr-Latn", englishName:"Serbian (Latin)",      name: "Srpski"},
   {code:"st",      englishName:"Sesotho",              name: "Sesotho"},
   {code:"sn",      englishName:"Shona",                name: "chiShona"},
   {code:"sd",      englishName:"Sindhi",               name: "ﻱﮅﻨﺳ"},
   {code:"si",      englishName:"Sinhala",              name: "සිංහල"},
   {code:"sk",      englishName:"Slovak",               name: "Slovenčina"},
   {code:"sl",      englishName:"Slovenian",            name: "Slovenščina"},
   {code:"so",      englishName:"Somali",               name: "Soomaali"},
   {code:"es",      englishName:"Spanish",              name: "Español"},
   {code:"su",      englishName:"Sundanese",            name: "Basa Sunda"},
   {code:"sw",      englishName:"Swahili",              name: "Kiswahili"},
   {code:"sv",      englishName:"Swedish",              name: "Svenska"},
   {code:"ty",      englishName:"Tahitian",             name: "Reo Tahiti"},
   {code:"tg",      englishName:"Tajik",                name: "Тоҷикӣ"},
   {code:"ta",      englishName:"Tamil",                name: "தமிழ்"},
   {code:"tt",      englishName:"Tatar",                name: "татарча"},
   {code:"te",      englishName:"Telugu",               name: "తెలుగు"},
   {code:"th",      englishName:"Thai",                 name: "ไทย"},
   {code:"to",      englishName:"Tongan",               name: "Lea faka-Tonga"},
   {code:"tr",      englishName:"Turkish",              name: "Türkçe"},
   {code:"udm",     englishName:"Udmurt",               name: "Удмурт"},
   {code:"uk",      englishName:"Ukrainian",            name: "Українська"},
   {code:"ur",      englishName:"Urdu",                 name: "ﻭﺩُﺭﺍُ"},
   {code:"uz",      englishName:"Uzbek",                name: "Oʻzbek tili"},
   {code:"vi",      englishName:"Vietnamese",           name: "Tiếng Việt"},
   {code:"cy",      englishName:"Welsh",                name: "Cymraeg"},
   {code:"xh",      englishName:"Xhosa",                name: "isiXhosa"},
   {code:"yi",      englishName:"Yiddish",              name: "שידיִי"},
   {code:"yo",      englishName:"Yoruba",               name: "Yorùbá"},
   {code:"yua",     englishName:"Yucatec Maya",         name: "Màaya T'àan"},
   {code:"zu",      englishName:"Zulu",                 name: "isiZulu"}
]

exports.hardcodedLanguages = hardcodedLanguages
