"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FORWARD_SLASH = exports.EN_DASH = exports.ELLIPSIS = exports.BLANK = exports.REFRESH_ICON = exports.APPLET_ICON = exports.SIGNAL_REPAINT = exports.SIGNAL_CLICKED = exports.SIGNAL_CHANGED = exports.UUID = void 0;
exports.UUID = "weather@mockturtl";
exports.SIGNAL_CHANGED = 'changed::';
exports.SIGNAL_CLICKED = 'clicked';
exports.SIGNAL_REPAINT = 'repaint';
exports.APPLET_ICON = "view-refresh-symbolic";
exports.REFRESH_ICON = "view-refresh";
exports.BLANK = '   ';
exports.ELLIPSIS = '...';
exports.EN_DASH = '\u2013';
exports.FORWARD_SLASH = '\u002F';
