#!/bin/bash
#
# /etc/init.d/turbonote

export DISPLAY=:0
case "$1" in
    start)
        echo "Iniciando serviço..."
	#/usr/share/cinnamon/applets/turbonote@iksws.com.br/turbonote-adds/server.py &
        ;; 
 
    stop)
        echo "Parando serviço..."
        fuser -n tcp -k 39681
        ;;
 
    restart)
        echo "Reiniciando serviço..."
        # comando para reiniciar o serviço
        ;;
 
    *)
        echo "Operação inválida"
        ;;
esac
