
const Applet = imports.ui.applet;
const Main = imports.ui.main;

function MyApplet(metadata) {
    this._init(metadata);
}

MyApplet.prototype = {
    __proto__: Applet.TextApplet.prototype,

    _init: function(metadata) {
        Applet.TextApplet.prototype._init.call(this, metadata);
        this.set_applet_tooltip(_("Vocabulary applet by rizanb"));
        this.updateVocabularyText();

        this.connect('clicked', this.on_applet_clicked.bind(this));
    },

    on_applet_clicked: function(event) {
        this.updateVocabularyText();
    },

    updateVocabularyText: function() {
        const randomIndex = Math.floor(Math.random() * vocab.length);
        const randomWord = vocab[randomIndex];

        this.set_applet_label(`${randomWord.word}: ${randomWord.meaning}`);
    }
};

const vocab = [
    { word: "philanthropist", meaning: "one who loves mankind" },
    { word: "introspection", meaning: "examining one's own thoughts and feelings" },
    { word: "antidote", meaning: "medicine used against a poison or a disease" },
    { word: "strive", meaning: "to make great efforts, to struggle" },
    { word: "ambidextrous", meaning: "able to use the left hand or the right equally well" },
    { word: "retrospective", meaning: "Looking back on past" },
    { word: "introvert", meaning: "one who turns towards himself" },
    { word: "malevolent", meaning: "malicious; evil; having or showing ill will" },
    { word: "ambiguous", meaning: "doubtful; uncertain" },
    { word: "aggravate", meaning: "make worse; irritate" },
    { word: "equilibrium", meaning: "state of being balanced" },
    { word: "entice", meaning: "attract, lure" },
    { word: "stray", meaning: "wander lose one's way" },
    { word: "precursors", meaning: "a person or thing that precedes, as in a process or job." },
    { word: "renovate", meaning: "restore something to better condition" },
    { word: "alleviate", meaning: "make (pain) easier to bear" },
    { word: "adorn", meaning: "add beauty; decorate" },
    { word: "curriculum", meaning: "course of study" },
    { word: "endeavor", meaning: "to make an effort, to try very hard" },
    { word: "abhor", meaning: "to hate; to detest" },
    { word: "agile", meaning: "active; quick-moving" },
    { word: "drowsiness", meaning: "feeling sleepy half asleep" },
    { word: "suffocate", meaning: "cause or have difficulty in breathing" },
    { word: "sequence", meaning: "succession connected line of" },
    { word: "scent", meaning: "smell (especially pleasant)" },
    { word: "braggart", meaning: "boastful" },
    { word: "disrobe", meaning: "undress" },
    { word: "xenophile", meaning: "a person who is attracted to foreign peoples cultures" },
    { word: "heterogeneous", meaning: "made up of different kinds" },
    { word: "connote", meaning: "Suggest or imply in addition to the precise, literal meaning" },
    { word: "massacre", meaning: "cruel killing of a large number of people" },
    { word: "submerge", meaning: "put under water liquid sink out of sight" },
    { word: "fragile", meaning: "easily injured broken or destroyed" },
    { word: "amalgamate", meaning: "mix; combine; unite societies" },
    { word: "sporadic", meaning: "happening from time to time" },
    { word: "conceal", meaning: "hide keep secret" },
    { word: "combustion", meaning: "process of burning" },
    { word: "conjoin", meaning: "to join together" },
    { word: "audacious", meaning: "Bold" },
    { word: "affinity", meaning: "close connection; relationship" },
    { word: "legacy", meaning: "Bequest or inheritance" },
    { word: "animosity", meaning: "strong dislike" },
    { word: "correlate", meaning: "have a mutual relation" },
    { word: "sadistic", meaning: "Cruel" },
    { word: "premature", meaning: "doing or happening something before the right time" },
    { word: "adulteration", meaning: "making unpure; poorer in quality" },
    { word: "indigenous", meaning: "native" },
    { word: "extinguish", meaning: "end the existence of/wipe or put out" },
    { word: "shunned", meaning: "avoided, kept away from" },
    { word: "surcharge", meaning: "additional load/charge" },
    { word: "edible", meaning: "fit to be eaten/not poisonous" },
    { word: "opaqueness", meaning: "dullness/not allowing light to pass through" },
    { word: "disallow", meaning: "refuse to allow or accept as a correct" },
    { word: "grumble", meaning: "to complain" },
    { word: "warrant", meaning: "authority written order guarantee" },
    { word: "anguish", meaning: "severe suffering" },
    { word: "console", meaning: "give comfort or sympathy to" },
    { word: "timid", meaning: "shy easily frightened" },
    { word: "impermeable", meaning: "that cannot be permeated" },
    { word: "extinct", meaning: "no longer active" },
    { word: "clientele", meaning: "customers" },
    { word: "accolade", meaning: "praise; approval" },
    { word: "ascend", meaning: "go or come up" },
    { word: "catalyst", meaning: "substance that causes speeding up" },
    { word: "somersault", meaning: "rolling backward or forward (not sideways) movement" },
    { word: "abide", meaning: "be faithful; to endure" },
    { word: "apt", meaning: "well-suited; quick-witted" },
    { word: "shallow", meaning: "little depth; not earnest" },
    { word: "inquest", meaning: "Legal or judicial inquiry, especially before a jury and especially made by a coroner into the cause of someone.s death" },
    { word: "brittle", meaning: "easily broken" },
    { word: "odor", meaning: "smell" },
    { word: "appease", meaning: "make quiet or calm" },
    { word: "offhand", meaning: "Without preparation or forethought" },
    { word: "scribble", meaning: "write hastily" },
    { word: "relapse", meaning: "fall back again" },
    { word: "dwarf", meaning: "person much smaller the usual size" },
    { word: "nihilism", meaning: "total rejection of all religious and moral beliefs" },
    { word: "rejuvenation", meaning: "becoming young in nature or appearance" },
    { word: "reminiscent", meaning: "suggest something in the past" },
    { word: "dangle", meaning: "hand or swing loosely" },
    { word: "negligent", meaning: "taking too little care" },
    { word: "ingest", meaning: "take in by swallowing" },
    { word: "arrogance", meaning: "proud; superior manner of behaviour" },
    { word: "reiterate", meaning: "say or do again several times" },
    { word: "acclaimed", meaning: "welcomed with shouts and approval" },
    { word: "divergence", meaning: "getting farther apart from a point" },
    { word: "vigorous", meaning: "strong energetic" },
    { word: "hospitable", meaning: "liking to give hospitality" },
    { word: "allegiance", meaning: "duty support loyalty" },
    { word: "abscond", meaning: "to go away suddenly (to avoid arrest)" },
    { word: "sawdust", meaning: "tiny bits of wood" },
    { word: "affable", meaning: "polite and friendly" },
    { word: "judicious", meaning: "sound in judgment; wise" },
    { word: "salvage", meaning: "the saving of property from loss" },
    { word: "sluggard", meaning: "lazy slow-moving person" },
    { word: "commuter", meaning: "person who travels regularly" },
    { word: "embezzle", meaning: "use in a wrong way for one's own benefit" },
    { word: "fragrant", meaning: "sweet-smelling" },
    { word: "weigh", meaning: "measure hoe heavy something is" },
    { word: "moderation", meaning: "quality of being limited; not extreme" },
    { word: "clot", meaning: "half-solid lump formed from liquid" },
    { word: "acumen", meaning: "Keen, quick, accurate insight or judgment" },
    { word: "flop", meaning: "fail/move/fall clumsily" },
    { word: "ossified", meaning: "turned to bone; hardened like bone; Inflexible" },
    { word: "commemorate", meaning: "keep the memory of" },
    { word: "narcissism", meaning: "Self-love" },
    { word: "eloquence", meaning: "fluent speaking skillful use of language" },
    { word: "steeply", meaning: "rising or falling sharply" },
    { word: "ameliorate", meaning: "improve; make better" },
    { word: "succumb", meaning: "yield, die" },
    { word: "enduring", meaning: "lasting" },
    { word: "invincible", meaning: "too strong to be defeated" },
    { word: "turmoil", meaning: "trouble disturbance" },
    { word: "sanity", meaning: "health of mind soundness of judgment" },
    { word: "torque", meaning: "twisting force causing rotation" },
    { word: "reconcile", meaning: "settle a quarrel restore peace" },
    { word: "derivative", meaning: "unoriginal; obtained from another source" },
    { word: "livid", meaning: "Furiously angry, enraged" },
    { word: "plea", meaning: "request" },
    { word: "benefactor", meaning: "person who has given help" },
    { word: "cryptic", meaning: "secret with a hidden meaning" },
    { word: "engulf", meaning: "swallow up" },
    { word: "enzyme", meaning: "catalyst" },
    { word: "sponge", meaning: "porous rubber for washing live at once expense" },
    { word: "defer", meaning: "postpone" },
    { word: "misogynist", meaning: "one who hates women/females" },
    { word: "infuriate", meaning: "fill with fury or rage" },
    { word: "renowned", meaning: "celebrated; famous" },
    { word: "riddle", meaning: "puzzling person or thing" },
    { word: "encapsulate", meaning: "enclose in capsule" },
    { word: "dormant", meaning: "in a state of inactivity but awaiting development" },
    { word: "hypocrisy", meaning: "falsely making oneself appear to be good" },
    { word: "grievous", meaning: "causing grief or pain; serious dire grave" },
    { word: "euphoria", meaning: "elation state of pleasant excitement" },
    { word: "fission", meaning: "splitting or division (esp. of cells)" },
    { word: "pertain", meaning: "belong as a part have reference" },
    { word: "tadpole", meaning: "form of a frog when it leaves the egg" },
    { word: "constrict", meaning: "make tight or smaller" },
    { word: "poseur", meaning: "a person who attempts to impress by acting unlike himself" },
    { word: "eradicate", meaning: "get rid of pull up by the roots" },
    { word: "evoke", meaning: "call up bring out" },
    { word: "shard", meaning: "A piece of broken pottery" },
    { word: "perish", meaning: "be destroyed decay" },
    { word: "disproof", meaning: "proof to the contrary" },
    { word: "impromptu", meaning: "without preparation" },
    { word: "extralegal", meaning: "outside the law" },
    { word: "volatile", meaning: "changeable inconstant fickle unstable explosive" },
    { word: "implicit", meaning: "implied though; not plainly expressed" },
    { word: "moribund", meaning: "in a dying state; near death" },
    { word: "perjury", meaning: "willful FALSE statement unlawful act" },
    { word: "mischievous", meaning: "harmful; causing mischief" },
    { word: "luminary", meaning: "star; light-giving body" },
    { word: "meticulous", meaning: "giving great attention to details" },
    { word: "flimsy", meaning: "lacking solidarity, strength" },
    { word: "suffice", meaning: "be enough" },
    { word: "parenthesis", meaning: "sentence within another one something separated" },
    { word: "gait", meaning: "a manner of walking, stepping, or running" },
    { word: "loll", meaning: "rest to sit or stand in a lazy way hang (dog's tongue)" },
    { word: "satiate", meaning: "satisfy fully" },
    { word: "sanction", meaning: "approval (by authority) penalty" },
    { word: "pluck", meaning: "pull the feathers off pick (e.g.. flowers)" },
    { word: "mesmerize", meaning: "hypnotize" },
    { word: "dupe", meaning: "cheat make a fool of" },
    { word: "erratic", meaning: "irregular in behaviour or opinion" },
    { word: "sobriety", meaning: "quality or condition of being sober" },
    { word: "sophisticated", meaning: "complex; subtle; refined" },
    { word: "connoisseur", meaning: "a person with good judgement (e.g.. in art)" },
    { word: "inclined", meaning: "directing the mind in a certain direction" },
    { word: "chisel", meaning: "steel tool for shaping materials" },
    { word: "pest", meaning: "destructive thing or a person who is nuisance" },
    { word: "alloy", meaning: "to debase by mixing with something inferior" },
    { word: "dislodge", meaning: "move force from the place occupied" },
    { word: "foolproof", meaning: "incapable of failure or error" },
    { word: "limp", meaning: "lacking strength; walking unevenly" },
    { word: "recuperate", meaning: "become strong after illness loss exhaustion" },
    { word: "paradigm", meaning: "a model example or pattern" },
    { word: "turbulence", meaning: "being uncontrollably violent" },
    { word: "permeate", meaning: "spread into every part of" },
    { word: "auxiliary", meaning: "helping; supporting" },
    { word: "mite", meaning: "A very small amount, portion, or particle" },
    { word: "complaisant", meaning: "trying to please; obliging" },
    { word: "spear", meaning: "weapon with a metal point on a long shaft" },
    { word: "predominate", meaning: "have more power than others" },
    { word: "bewilder", meaning: "puzzle; confuse" },
    { word: "abysmal", meaning: "extreme bad" },
    { word: "partisan", meaning: "one-sided committed to a party biased or prejudiced" },
    { word: "gullible", meaning: "easily gulled" },
    { word: "fidelity", meaning: "loyalty accuracy" },
    { word: "dullard", meaning: "a stupid, insensitive person" },
    { word: "yarn", meaning: "tale story fibers for knitting" },
    { word: "foster", meaning: "nurture; care for" },
    { word: "articulate", meaning: "speak distinctly; connect by joints" },
    { word: "fleet", meaning: "number of ships; quick-moving" },
    { word: "gallant", meaning: "brave,behaves well with women" },
    { word: "vivacious", meaning: "lively high-spirited" },
    { word: "recitals", meaning: "a number of performance of music" },
    { word: "coagulation", meaning: "change to a thick and solid state" },
    { word: "patron", meaning: "regular customer person who gives support" },
    { word: "abstruse", meaning: "difficult to comprehend; obscure" },
    { word: "malleable", meaning: "yielding easily shaped; moldable; adapting" },
    { word: "impede", meaning: "hinder; get in the way of" },
    { word: "forgery", meaning: "counterfeit" },
    { word: "elaborate", meaning: "worked out with much care in great detail" },
    { word: "Lambaste", meaning: "attack verbally" },
    { word: "liberality", meaning: "free giving; generosity" },
    { word: "solvent", meaning: "of the power of forming a solution" },
    { word: "tractable", meaning: "easily controlled or guided" },
    { word: "calipers", meaning: "metal supports attached to the legs measuring instrument" },
    { word: "concur", meaning: "agree in opinion happen together" },
    { word: "redeem", meaning: "get back by payment compensate" },
    { word: "aberration", meaning: "straying away from what is normal" },
    { word: "indistinct", meaning: "not easily heard; seen clearly marked" },
    { word: "resuscitation", meaning: "coming back to consciousness" },
    { word: "pivotal", meaning: "of great importance (others depend on it)" },
    { word: "dote", meaning: "show much fondness center one's attention" },
    { word: "knit", meaning: "draw together; unite firmly" },
    { word: "stride", meaning: "walk with long steps" },
    { word: "diabolical", meaning: "having the qualities of a devil" },
    { word: "sheath", meaning: "cover for the blade of a weapon or a tool" },
    { word: "unscathed", meaning: "unharmed unhurt" },
    { word: "immutable", meaning: "that cannot be changed" },
    { word: "ail", meaning: "to cause pain, uneasiness, or trouble to." },
    { word: "jabber", meaning: "talk excitedly; utter rapidly" },
    { word: "ambivalent", meaning: "having both of two contrary meanings" },
    { word: "centurion", meaning: "leader of a unit of 100 soldiers" },
    { word: "tonic", meaning: "something giving strength or energy" },
    { word: "cumbersome", meaning: "burdensome; heavy and awkward to carry" },
    { word: "implosion", meaning: "collapse; bursting inward" },
    { word: "cordial", meaning: "warm and sincere" },
    { word: "brass", meaning: "yellow metal (mixing copper and zinc)" },
    { word: "evasive", meaning: "tending to evade" },
    { word: "enigma", meaning: "something that is puzzling" },
    { word: "feud", meaning: "bitter quarrel over a long period of time" },
    { word: "reverent", meaning: "feeling or showing deep respect" },
    { word: "buoyant", meaning: "able to float; light-hearted" },
    { word: "turquoise", meaning: "greenish-blue precious stone" },
    { word: "euthanasia", meaning: "easy and painless death" },
    { word: "chortle", meaning: "loud chuckle of pleasure or amusement" },
    { word: "eulogy", meaning: "formal praise panegyric" },
    { word: "bogus", meaning: "sham; counterfeit; not genuine" },
    { word: "skit", meaning: "short piece of humorous writing" },
    { word: "substantiation", meaning: "giving facts to support (statement)" },
    { word: "superimpose", meaning: "put something on the top" },
    { word: "decree", meaning: "order given by authority" },
    { word: "misanthrope", meaning: "person who hates mankind" },
    { word: "savor", meaning: "taste flavor something" },
    { word: "dexterity", meaning: "skill (esp. in handling)" },
    { word: "incongruous", meaning: "out of place; not in harmony or agreement" },
    { word: "concoct", meaning: "invent, prepare by mixing together" },
    { word: "swerve", meaning: "change direction suddenly" },
    { word: "underbid", meaning: "make a lower bid then somebody else" },
    { word: "convoluted", meaning: "complicated;coiled; twisted" },
    { word: "indefatigability", meaning: "not easily exhaustible; tirelessness" },
    { word: "derogatory", meaning: "insulting; tending to damage" },
    { word: "indulgent", meaning: "inclined to indulge" },
    { word: "coalescing", meaning: "coming together and uniting into one substance" },
    { word: "boisterous", meaning: "noisy; restraint" },
    { word: "irate", meaning: "angry" },
    { word: "hoax", meaning: "mischievous trick played to deceive" },
    { word: "cognizant", meaning: "being fully aware of" },
    { word: "unearth", meaning: "discover and bring to light" },
    { word: "repel", meaning: "refuse to accept/cause dislike" },
    { word: "retrograde", meaning: "receding" },
    { word: "imminent", meaning: "likely to come or happen soon" },
    { word: "gust", meaning: "outburst of feeling; sudden rain wind fire etc." },
    { word: "repulsive", meaning: "causing a feeling of disgust" },
    { word: "apartheid", meaning: "brutal racial discrimination" },
    { word: "multifarious", meaning: "varied; motley; greatly diversified" },
    { word: "plunge", meaning: "move quickly suddenly and with force" },
    { word: "presentiment", meaning: "anticipatory fear; premonition" },
    { word: "writ", meaning: "written order" },
    { word: "soggy", meaning: "heavy with water" },
    { word: "warmonger", meaning: "person who stirs up war" },
    { word: "treacherous", meaning: "not to be trusted, perfidious" },
    { word: "woo", meaning: "try to win" },
    { word: "repertoire", meaning: "A stock of plays, dances, or pieces that a company or a performer knows or is prepared to perform" },
    { word: "nary", meaning: "not any; no;" },
    { word: "pinchbeck", meaning: "An alloy of zinc and copper used as imitation gold; A cheap imitation" },
    { word: "defiance", meaning: "open disobedience or resistance" },
    { word: "irrevocable", meaning: "final and unalterable" },
    { word: "asterisk", meaning: "the mark * (e.g.. omitted letters)" },
    { word: "plummet", meaning: "fall plunge steeply" },
    { word: "reciprocity", meaning: "granting of privileges in return for similar" },
    { word: "coerce", meaning: "compel to force to make obedient" },
    { word: "valiant", meaning: "brave" },
    { word: "candid", meaning: "frank; straight-forward" },
    { word: "frantic", meaning: "wildly excited with joy; pain; anxiety" },
    { word: "torment", meaning: "severe pain or suffering" },
    { word: "earthenware", meaning: "dishes made of baked clay" },
    { word: "revere", meaning: "have deep respect for" },
    { word: "counterfeit", meaning: "forgery" },
    { word: "proliferate", meaning: "grow reproduce by rapid multification" },
    { word: "precursory", meaning: "preliminary; anticipating" },
    { word: "squander", meaning: "spend wastefully" },
    { word: "vindictive", meaning: "having a desire to revenge" },
    { word: "alcove", meaning: "recess/partially enclosed place" },
    { word: "exculpate", meaning: "to clear from a charge of guilt" },
    { word: "pinch", meaning: "be too tight take between the thumb and finger" },
    { word: "deplete", meaning: "use until none remains" },
    { word: "personable", meaning: "pleasing in appearance attractive " }
];