// This script reads the the version from package.json.
// The script is triggered on `npm run build` (prebuild script)
const fs = require("fs")

const packageJson = require("../package.json")
const appletVersion = packageJson.version

const content = `// This file is auto-generated by set-version.cjs
export const APPLET_VERSION = "${appletVersion}"
`
fs.writeFileSync("./src/consts/version.ts", content)

// Update the version in settings-schema.json ("keyVersion"."description")
const settingsSchemaPath = "./files/fish@kriegcc/settings-schema.json"
const settingsSchema = JSON.parse(fs.readFileSync(settingsSchemaPath, "utf-8"))
settingsSchema.keyVersion.description = `v${appletVersion}`
fs.writeFileSync(settingsSchemaPath, JSON.stringify(settingsSchema, null, 2))

// Update version in metadata.json.
const metadataPath = "./files/fish@kriegcc/metadata.json"
const metadata = JSON.parse(fs.readFileSync(metadataPath, "utf-8"))
metadata.version = appletVersion
fs.writeFileSync(metadataPath, JSON.stringify(metadata, null, 2))
