// This script reads the the version from package.json, the commit hash and date from Git and makes the information available as constants.
// The script is triggered on `npm run build` (prebuild script)
const { execSync } = require("child_process")
const fs = require("fs")

const packageJson = require("../package.json")

const appletVersion = packageJson.version

// filter commits by the fish applet directory
const commitId = execSync("git log -n 1 --pretty=format:%h -- ../fish@kriegcc").toString().trim()
const commitDate = execSync("git log -n 1 --pretty=format:%cd --date=format:%Y-%m-%d -- ../fish@kriegcc")
  .toString()
  .trim()

const content = `// This file is auto-generated by set-version.cjs
export const APPLET_VERSION = "${appletVersion}"
export const COMMIT_ID = "${commitId}"
export const COMMIT_DATE = "${commitDate}"
`
fs.writeFileSync("./src/consts/version.ts", content)

// Update the version in settings-schema.json ("keyVersion"."description").
// I could not find an adequate setting widget which allows to set it programmatically in applet code (setValue)
// "entry" or "textview" would work, but they did not look good in this case.
const settingsSchemaPath = "./files/fish@kriegcc/settings-schema.json"
const settingsSchema = JSON.parse(fs.readFileSync(settingsSchemaPath, "utf-8"))
settingsSchema.keyVersion.description = `v${appletVersion}-${commitId} (${commitDate})`
fs.writeFileSync(settingsSchemaPath, JSON.stringify(settingsSchema, null, 2))

// Update version in metadata.json.
const metadataPath = "./files/fish@kriegcc/metadata.json"
const metadata = JSON.parse(fs.readFileSync(metadataPath, "utf-8"))
metadata.version = appletVersion
fs.writeFileSync(metadataPath, JSON.stringify(metadata, null, 2))
