# This is a basic workflow to help you get started with Actions

name: Update Translation Status Tables

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-tables:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Generate Translation Status Tables
        run: |
          sudo apt-get update -y >/dev/null 2>&1
          sudo apt-get install -y python3 gettext >/dev/null 2>&1
          cd .translation-tables
          python3 translation-tables.py --quiet
          git config user.name "NikoKrause"
          git config user.email "8415124+NikoKrause@users.noreply.github.com"
          git add .
          git commit --quiet -m "Update Translation Status Tables (GitHub Actions)"
          git push -f origin master:translation-status-tables
